// +build !ignore_autogenerated

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GTP5GModule) DeepCopyInto(out *GTP5GModule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GTP5GModule.
func (in *GTP5GModule) DeepCopy() *GTP5GModule {
	if in == nil {
		return nil
	}
	out := new(GTP5GModule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GTP5GModule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GTP5GModuleList) DeepCopyInto(out *GTP5GModuleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GTP5GModule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GTP5GModuleList.
func (in *GTP5GModuleList) DeepCopy() *GTP5GModuleList {
	if in == nil {
		return nil
	}
	out := new(GTP5GModuleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GTP5GModuleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GTP5GModuleSpec) DeepCopyInto(out *GTP5GModuleSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GTP5GModuleSpec.
func (in *GTP5GModuleSpec) DeepCopy() *GTP5GModuleSpec {
	if in == nil {
		return nil
	}
	out := new(GTP5GModuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GTP5GModuleStatus) DeepCopyInto(out *GTP5GModuleStatus) {
	*out = *in
	if in.InstalledNodes != nil {
		in, out := &in.InstalledNodes, &out.InstalledNodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.FailedNodes != nil {
		in, out := &in.FailedNodes, &out.FailedNodes
		*out = make([]NodeFailure, len(*in))
		copy(*out, *in)
	}
	in.LastUpdateTime.DeepCopyInto(&out.LastUpdateTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GTP5GModuleStatus.
func (in *GTP5GModuleStatus) DeepCopy() *GTP5GModuleStatus {
	if in == nil {
		return nil
	}
	out := new(GTP5GModuleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeFailure) DeepCopyInto(out *NodeFailure) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeFailure.
func (in *NodeFailure) DeepCopy() *NodeFailure {
	if in == nil {
		return nil
	}
	out := new(NodeFailure)
	in.DeepCopyInto(out)
	return out
}
