name: Build Dependencies
description: |
  Install build dependencies to test and compile tracee artifacts
inputs:
  go-version:
    description: go version
    default: "1.21"
runs:
  using: composite
  steps:
    - name: Setup Go
      uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
      with:
        go-version: "${{ inputs.go-version }}"
    - name: Install Compilers & Formatters
      run: |
        sudo apt-get update
        sudo apt-get install --yes bsdutils
        sudo apt-get install --yes build-essential
        sudo apt-get install --yes pkgconf
        sudo apt-get install --yes llvm-17 llvm-18 clang-17 clang-format-17
        sudo apt-get install --yes libbpf-dev libelf-dev libzstd-dev zlib1g-dev
        sudo apt-get install --yes virtme-ng
        sudo apt-get install --yes gcc-multilib
        sudo apt-get install --yes systemtap-sdt-dev
        sudo apt-get install --yes python3 python3-pip ninja-build
        sudo apt-get install --yes libseccomp-dev protobuf-compiler
        pip3 install --user meson
        for tool in "clang" "clang-format" "llc"
        do
          sudo rm -f /usr/bin/$tool
          sudo ln -s /usr/bin/$tool-17 /usr/bin/$tool
        done
        # Install llvm-strip symlink to version 18 (scx meson.build requires llvm-strip executable)
        sudo update-alternatives --install /usr/bin/llvm-strip llvm-strip /usr/bin/llvm-strip-18 100
      shell: bash
    - name: Install Schtest
      run: |
        if [ ! -d "schtest" ]; then
          git clone https://github.com/sched-ext/schtest.git schtest
        else
          cd schtest && git pull || true
        fi
      shell: bash
