apiVersion: apps/v1
kind: Deployment
metadata:
  name: gtp5g-operator
  namespace: gtp5g-operator-system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      serviceAccountName: gtp5g-operator
      containers:
      - command:
        - /manager
        args:
        - --leader-elect
        image: localhost:5000/gtp5g-operator:latest
        name: manager
        env:
        - name: INSTALLER_IMAGE
          value: "localhost:5000/gtp5g-installer:latest"
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        - containerPort: 8081
          name: health
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
      terminationGracePeriodSeconds: 10
