apiVersion: v1
kind: Service
metadata:
  name: gtp5g-operator-metrics
  namespace: gtp5g-operator-system
  labels:
    control-plane: controller-manager
spec:
  selector:
    control-plane: controller-manager
  ports:
  - name: metrics
    port: 8080
    protocol: TCP
    targetPort: 8080
